// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  bookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'generated-index',
        title: 'Introduction',
        description: 'Learn about the basics of Physical AI and Humanoid Robotics.',
        slug: '/introduction',
      },
      items: [{type: 'autogenerated', dirName: 'introduction'}],
    },
    {
      type: 'category',
      label: 'Module 1: Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
        title: 'Module 1: Robotic Nervous System (ROS 2)',
        description: 'Explore the fundamentals of ROS 2 for humanoid robotics.',
        slug: '/module-1-ros2',
      },
      items: [{type: 'autogenerated', dirName: 'module-1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin Simulation',
      link: {
        type: 'generated-index',
        title: 'Module 2: Digital Twin Simulation',
        description: 'Dive into digital twin concepts and simulation environments.',
        slug: '/module-2-digital-twin',
      },
      items: [{type: 'autogenerated', dirName: 'module-2-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain (NVIDIA Isaac)',
      link: {
        type: 'generated-index',
        title: 'Module 3: AI Robot Brain (NVIDIA Isaac)',
        description: 'Understand how NVIDIA Isaac powers AI robot brains.',
        slug: '/module-3-isaac',
      },
      items: [{type: 'autogenerated', dirName: 'module-3-isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision Language Action',
      link: {
        type: 'generated-index',
        title: 'Module 4: Vision Language Action',
        description: 'Discover Vision Language Action pipelines for humanoids.',
        slug: '/module-4-vla',
      },
      items: [{type: 'autogenerated', dirName: 'module-4-vla'}],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      link: {
        type: 'generated-index',
        title: 'Capstone Project',
        description: 'Apply your knowledge in a comprehensive capstone project.',
        slug: '/capstone',
      },
      items: [{type: 'autogenerated', dirName: 'capstone'}],
    },
    {
      type: 'link',
      label: 'Glossary',
      href: '/glossary',
    },
    {
      type: 'link',
      label: 'Appendix',
      href: '/appendix',
    },
    {
      type: 'link',
      label: 'Assessments',
      href: '/assessments',
    },
  ],
};

export default sidebars;
